apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps-main
spec:
  destination:
    server: in-cluster
    namespace: argocd
  source:
    path: apps
    repoURL: https://github.com/alhennessey92/traders_guild_dev
    targetRevision: HEAD
    directory: {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true