architecture: replication
auth:
  enabled: false
sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  downAfterMilliseconds: 5000
  failoverTimeout: 10000
persistence:
  enabled: true
  storageClass: standard
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m