apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-kong-lb
  namespace: argocd
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes to check if scaling down occurred
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: delete-kong
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - |
                echo "Checking for scaling down..."
                kubectl get events -n kube-system | grep "ScalingDown" | grep "nodepool-name"
                if [ $? -eq 0 ]; then
                  echo "Scaling down detected, deleting Kong LoadBalancer..."
                  kubectl delete svc kong-proxy -n kong
                fi