apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubectl-service-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-watcher-role
rules:
  - apiGroups: [""]
    resources: ["events", "services"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "sync"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-watcher-rolebinding
subjects:
  - kind: ServiceAccount
    name: event-watcher-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: event-watcher-role
  apiGroup: rbac.authorization.k8s.io