apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-service-account
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-watcher-sa
  namespace: kube-system