apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-kong-argocd
  namespace: argocd
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes to check if scaling up occurred
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: sync-kong
            image: argoproj/argocd:latest
            command:
              - /bin/sh
              - -c
              - |
                echo "Syncing Kong deployment via ArgoCD..."
                argocd app sync kong --grpc-web