apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "yourpassword"