replicaCount: 1

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

persistence:
  enabled: true
  size: 10Gi

  auth:
    existingSecret: timescaledb-secret
    postgresPasswordKey: postgresql-password
    replicationPasswordKey: replication-password