apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: kong
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  sources:
    # Chart from Chart Repo
    - chart: kong
      repoURL: https://charts.konghq.com
      targetRevision: 2.47.0
      helm:
        valueFiles:
        - $values/apps/kong/values.yaml
    # Values from Git
    - repoURL: 'https://github.com/alhennessey92/traders_guild_dev'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true