admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001  # Ensure it's accessible within the cluster
  tls:
    enabled: false  # Disable TLS for simplicity (use HTTPS if needed)
    
ingressController:
  enabled: true
  installCRDs: true
  env:
    database: "off"
    proxy_access_log: /dev/stdout
    admin_gui_access_log: /dev/stdout
    admin_access_log: /dev/stdout
    admin_error_log: /dev/stderr
    proxy_error_log: /dev/stderr
    KONG_DATABASE: "off"
    KONG_ADMIN_LISTEN: "0.0.0.0:8001"

proxy:
  type: LoadBalancer

env:
  KONG_PLUGINS: bundled, jwt, rate-limiting

serviceMonitor:
  enabled: true


# readinessProbe:
#   httpGet:
#     path: /status
#     port: 8001  # Ensure this is correct for Admin API
#   initialDelaySeconds: 10
#   periodSeconds: 5