admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001  # Ensure it's accessible within the cluster
  tls:
    enabled: false  # Disable TLS for simplicity (use HTTPS if needed)

ingressController:
  enabled: true
  installCRDs: true
  env:
    database: "off"
    proxy_access_log: /dev/stdout
    admin_gui_access_log: /dev/stdout
    admin_access_log: /dev/stdout
    admin_error_log: /dev/stderr
    proxy_error_log: /dev/stderr
    KONG_DATABASE: "off"
    KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    KONG_PORT_MAPS: "80:8000,443:8443"  # Maps external ports to Kong's internal ones

proxy:
  type: LoadBalancer  # Change to LoadBalancer
  loadBalancerIP: "34.70.170.151"  # Replace with your reserved static IP from GCP
  annotations: {}
  http:
    enabled: true
  tls:
    enabled: true

env:
  KONG_PLUGINS: bundled, jwt, rate-limiting  # Ensure JWT and rate limiting are available

serviceMonitor:
  enabled: true







# readinessProbe:
#   httpGet:
#     path: /status
#     port: 8001  # Ensure this is correct for Admin API
#   initialDelaySeconds: 10
#   periodSeconds: 5