apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  namespace: timescaledb
type: Opaque
data:
  postgresql-password: cG9zdGdyZXM=   # Base64 encoded "postgres"
  replication-password: cmVwbGljYXRl   # Base64 encoded "replicate"